translate('Genesis', $st, 'sys');
translate('Exodus', $st, 'sys');
translate('Leviticus', $st, 'sys');
translate('Numbers', $st, 'sys');
translate('Deuteronomy', $st, 'sys');
translate('Joshua', $st, 'sys');
translate('Judges', $st, 'sys');
translate('Ruth', $st, 'sys');
translate('1 Samuel', $st, 'sys');
translate('2 Samuel', $st, 'sys');
translate('1 Kings', $st, 'sys');
translate('2 Kings', $st, 'sys');
translate('1 Chronicles', $st, 'sys');
translate('2 Chronicles', $st, 'sys');
translate('Ezra', $st, 'sys');
translate('Nehemiah', $st, 'sys');
translate('Esther', $st, 'sys');
translate('Job', $st, 'sys');
translate('Psalms', $st, 'sys');
translate('Proverbs', $st, 'sys');
translate('Ecclesiastes', $st, 'sys');
translate('Song of Solomon', $st, 'sys');
translate('Isaiah', $st, 'sys');
translate('Jeremiah', $st, 'sys');
translate('Lamentations', $st, 'sys');
translate('Ezekiel', $st, 'sys');
translate('Daniel', $st, 'sys');
translate('Hosea', $st, 'sys');
translate('Joel', $st, 'sys');
translate('Amos', $st, 'sys');
translate('Obadiah', $st, 'sys');
translate('Jonah', $st, 'sys');
translate('Micah', $st, 'sys');
translate('Nahum', $st, 'sys');
translate('Habukkuk', $st, 'sys');
translate('Zephaniah', $st, 'sys');
translate('Haggai', $st, 'sys');
translate('Zechariah', $st, 'sys');
translate('Malachi', $st, 'sys');
translate('Matthew', $st, 'sys');
translate('Mark', $st, 'sys');
translate('Luke', $st, 'sys');
translate('John', $st, 'sys');
translate('Acts', $st, 'sys');
translate('Romans', $st, 'sys');
translate('1 Corinthians', $st, 'sys');
translate('2 Corinthians', $st, 'sys');
translate('Galatians', $st, 'sys');
translate('Ephesians', $st, 'sys');
translate('Philippians', $st, 'sys');
translate('Colossians', $st, 'sys');
translate('1 Thessalonians', $st, 'sys');
translate('2 Thessalonians', $st, 'sys');
translate('1 Timothy', $st, 'sys');
translate('2 Timothy', $st, 'sys');
translate('Titus', $st, 'sys');
translate('Philemon', $st, 'sys');
translate('Hebrews', $st, 'sys');
translate('James', $st, 'sys');
translate('1 Peter', $st, 'sys');
translate('2 Peter', $st, 'sys');
translate('1 John', $st, 'sys');
translate('2 John', $st, 'sys');
translate('3 John', $st, 'sys');
translate('Jude', $st, 'sys');
translate('Revelation', $st, 'sys');
